const state={family:'all',difficulty:'all',query:'',compare:[]};
const $=selector=>document.querySelector(selector);
const els={grid:$('#materialsGrid'),family:$('#familyFilter'),difficulty:$('#difficultyFilter'),search:$('#searchInput'),reset:$('#resetFilters'),visible:$('#visibleCount'),total:$('#materialCount'),empty:$('#emptyState'),chips:$('#familyChips'),dialog:$('#materialDialog'),dialogContent:$('#dialogContent'),compare:$('#compareTray'),clearCompare:$('#clearCompare'),modelMaterial:$('#modelMaterial'),supportResult:$('#supportResult'),questGrid:$('#questGrid'),questResult:$('#questResult'),menuToggle:$('.menu-toggle'),nav:$('.nav'),sound:$('.sound-toggle'),popular:$('#popularGrid'),special:$('#specialGrid'),backToTop:$('#backToTop')};
let soundEnabled=false;
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const families=[...new Set(MATERIALS.map(m=>m.family))].sort((a,b)=>a.localeCompare(b,'ru'));
const popularNames=['PLA','PLA+','HT-PLA','PETG','PCTG','ABS','ASA','HIPS','TPU 95A','PA6 Nylon','PA12 Nylon','CoPA','PC','PC-ABS','PP','POM / Acetal','PEI / ULTEM','PEEK','PEKK','PVB','SBS','CPE','PET / PETT','PA-CF'];
const specialItems=[['CF','▧','карбон'],['GF','◫','стекло'],['Wood','▥','дерево'],['Metal','●','металл'],['Glow','✦','светится'],['Conductive','ϟ','проводящий'],['ESD','⚠','антистатик'],['FR','♨','огнестойкий'],['LW-PLA','↟','лёгкий'],['Magnetic','∩','магнитный'],['Antibacterial','✚','антибактериальный'],['Castable','♜','выжигаемый'],['PVA','◉','растворимый'],['BVOH','≋','водорастворимый'],['Breakaway','✂','отрывной'],['AquaSys','≈','support']];
function stars(value,max=5){return `<span class="rating" aria-label="${value} из ${max}">${'■'.repeat(value)}${'□'.repeat(max-value)}</span>`}
function difficultyLabel(value){return ['','Просто','Средне','Сложно','Промышленно'][value]||'—'}
function beep(freq=440,duration=.035){if(!soundEnabled)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='square';osc.frequency.value=freq;gain.gain.value=.018;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration);osc.addEventListener('ended',()=>ctx.close(),{once:true})}
function findMaterial(name){const q=name.toLowerCase();return MATERIALS.find(m=>m.name.toLowerCase()===q)||MATERIALS.find(m=>m.name.toLowerCase().includes(q))||MATERIALS.find(m=>q.includes(m.name.toLowerCase()))}
function fillFilters(){els.total.textContent=MATERIALS.length;families.forEach(name=>{els.family.add(new Option(name,name))});['Все',...families].forEach((name,index)=>{const button=document.createElement('button');button.className=`chip${index===0?' active':''}`;button.dataset.family=index===0?'all':name;button.textContent=name;els.chips.append(button)})}
function renderPopular(){const featured=popularNames.map(findMaterial).filter((m,i,a)=>m&&a.indexOf(m)===i).slice(0,24);els.popular.innerHTML=featured.map(m=>`<button class="popular-card" type="button" data-material="${m.name}" style="--accent:${m.color}"><span class="mini-spool"></span><span><b>${m.name}</b><small>${m.desc}</small></span></button>`).join('');els.special.innerHTML=specialItems.map(([query,icon,text])=>`<button class="special-card" type="button" data-query="${query}"><span>${icon}</span><b>${query}</b><small>${text}</small></button>`).join('')}
function matches(m){const hay=[m.name,m.family,m.desc,...m.uses,m.support].join(' ').toLowerCase();return(state.family==='all'||m.family===state.family)&&(state.difficulty==='all'||String(m.difficulty)===state.difficulty)&&(!state.query||hay.includes(state.query))}
function renderMaterials(){const list=MATERIALS.filter(matches);els.visible.textContent=list.length;els.empty.hidden=!!list.length;els.grid.innerHTML=list.map(m=>`<article class="material-card reveal" style="--accent:${m.color}" tabindex="0" data-name="${m.name}"><div class="card-top"><span class="spool-icon" aria-hidden="true"><i></i></span><span class="family-tag">${m.family}</span></div><h3>${m.name}</h3><p>${m.desc}</p><div class="temp-row"><span>Сопло <b>${m.nozzle}°</b></span><span>Стол <b>${m.bed}°</b></span></div><div class="card-stats"><span>STR ${stars(m.strength)}</span><span>HEAT ${stars(m.heat)}</span></div><div class="card-actions"><button class="details-btn" data-action="details" type="button">Подробнее</button><button class="compare-btn ${state.compare.includes(m.name)?'active':''}" data-action="compare" type="button">${state.compare.includes(m.name)?'✓ В сравнении':'+ Сравнить'}</button></div></article>`).join('');observeReveals(els.grid.querySelectorAll('.reveal'))}
function openDetails(name){const m=findMaterial(name);if(!m)return;els.dialogContent.innerHTML=`<div class="dialog-title" style="--accent:${m.color}"><span class="spool-icon big"><i></i></span><div><small>${m.family}</small><h2>${m.name}</h2></div></div><p class="dialog-desc">${m.desc}</p><div class="detail-grid"><span><small>Сопло</small><b>${m.nozzle} °C</b></span><span><small>Стол</small><b>${m.bed} °C</b></span><span><small>Камера</small><b>${m.chamber}</b></span><span><small>Сушка</small><b>${m.dry}</b></span></div><div class="stat-bars">${[['strength','Прочность'],['flex','Гибкость'],['heat','Теплостойкость']].map(([key,label])=>`<div><span>${label}</span><i><b style="width:${m[key]*20}%"></b></i><em>${m[key]}/5</em></div>`).join('')}<div><span>Сложность</span><i><b style="width:${m.difficulty*25}%"></b></i><em>${difficultyLabel(m.difficulty)}</em></div></div><div class="dialog-columns"><div><small>Подходит для</small><ul>${m.uses.map(use=>`<li>${use}</li>`).join('')}</ul></div><div><small>Интерфейс поддержек</small><p>${m.support}</p></div></div>`;els.dialog.showModal();beep(640)}
window.openDetails=openDetails;
function toggleCompare(name){if(state.compare.includes(name))state.compare=state.compare.filter(item=>item!==name);else if(state.compare.length<3)state.compare.push(name);else{els.compare.animate([{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'none'}],{duration:180});beep(150,.08);return}renderMaterials();renderCompare();beep(520)}
function renderCompare(){if(!state.compare.length){els.compare.innerHTML='<div class="compare-placeholder">Пока пусто. Выбери материалы в каталоге.</div>';return}const list=state.compare.map(findMaterial).filter(Boolean);els.compare.innerHTML=`<div class="compare-table" style="--cols:${list.length}"><div class="compare-labels"><b>Параметр</b><span>Сопло</span><span>Стол</span><span>Сушка</span><span>Прочность</span><span>Гибкость</span><span>Тепло</span><span>Сложность</span><span>Support</span></div>${list.map(m=>`<div class="compare-column" style="--accent:${m.color}"><b>${m.name}<button data-remove="${m.name}" aria-label="Убрать ${m.name}">×</button></b><span>${m.nozzle} °C</span><span>${m.bed} °C</span><span>${m.dry}</span><span>${stars(m.strength)}</span><span>${stars(m.flex)}</span><span>${stars(m.heat)}</span><span>${difficultyLabel(m.difficulty)}</span><span>${m.support}</span></div>`).join('')}</div>`}
function updateSupport(){const name=els.modelMaterial.value,m=findMaterial(name),rule=SUPPORT_MAP[name]||{best:m?.support||'Материал модели с увеличенным Z-зазором',alternatives:['Фирменный Breakaway после теста'],note:'Для этой пары нет универсального рецепта — сначала напечатай небольшой тест.'};els.supportResult.innerHTML=`<div class="selected-material" style="--accent:${m?.color||'#fff'}"><span class="spool-icon"><i></i></span><div><small>Модель</small><b>${name}</b></div></div><div class="support-arrow">↓</div><div class="support-best"><small>Лучший стартовый вариант</small><strong>${rule.best}</strong></div>${rule.alternatives?.length?`<div class="support-alt"><small>Альтернативы</small><span>${rule.alternatives.join(' · ')}</span></div>`:''}<p class="support-note">${rule.note}</p>`}
function renderQuests(){els.questGrid.innerHTML=QUESTS.map(q=>`<button class="quest-card reveal" data-quest="${q.id}" type="button"><span>${q.icon}</span><b>${q.title}</b><small>${q.material}</small></button>`).join('');observeReveals(els.questGrid.querySelectorAll('.reveal'))}
function selectQuest(id){const q=QUESTS.find(item=>item.id===id);if(!q)return;document.querySelectorAll('.quest-card').forEach(card=>card.classList.toggle('active',card.dataset.quest===id));const m=findMaterial(q.material);els.questResult.innerHTML=`<span class="quest-avatar" style="--accent:${m?.color}">${q.icon}</span><div><small>${q.title}</small><h3>${q.material}</h3><p>${q.text}</p><button type="button" data-open-material="${q.material}">Открыть карточку</button></div>`;beep(720)}
function setFamily(name){state.family=name;els.family.value=name;document.querySelectorAll('.chip').forEach(chip=>chip.classList.toggle('active',chip.dataset.family===name));renderMaterials()}
let revealObserver;
function observeReveals(nodes){if(reduceMotion){nodes.forEach(node=>node.classList.add('visible'));return}if(!revealObserver)revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -25px'});nodes.forEach(node=>revealObserver.observe(node))}
function loadEasterEggs(){const link=document.createElement('link');link.rel='stylesheet';link.href='easter-eggs.css?v=4.0.0';document.head.append(link);const script=document.createElement('script');script.src='easter-eggs.js?v=4.0.0';script.defer=true;document.body.append(script)}
function bindEvents(){els.search.addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderMaterials()});els.family.addEventListener('change',e=>setFamily(e.target.value));els.difficulty.addEventListener('change',e=>{state.difficulty=e.target.value;renderMaterials()});els.reset.addEventListener('click',()=>{state.family='all';state.difficulty='all';state.query='';els.search.value='';els.family.value='all';els.difficulty.value='all';setFamily('all');beep(300)});els.chips.addEventListener('click',e=>{const chip=e.target.closest('[data-family]');if(chip)setFamily(chip.dataset.family)});els.grid.addEventListener('click',e=>{const card=e.target.closest('.material-card');if(!card)return;const action=e.target.closest('button')?.dataset.action;if(action==='compare')toggleCompare(card.dataset.name);else openDetails(card.dataset.name)});els.grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();openDetails(e.target.closest('.material-card')?.dataset.name)}});$('.dialog-close').addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close()});els.compare.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b)toggleCompare(b.dataset.remove)});els.clearCompare.addEventListener('click',()=>{state.compare=[];renderCompare();renderMaterials()});els.modelMaterial.addEventListener('change',updateSupport);els.questGrid.addEventListener('click',e=>{const card=e.target.closest('[data-quest]');if(card)selectQuest(card.dataset.quest)});els.questResult.addEventListener('click',e=>{const b=e.target.closest('[data-open-material]');if(b)openDetails(b.dataset.openMaterial)});els.menuToggle.addEventListener('click',()=>{const open=els.nav.classList.toggle('open');els.menuToggle.setAttribute('aria-expanded',String(open))});els.nav.addEventListener('click',e=>{if(e.target.closest('a'))els.nav.classList.remove('open')});els.sound.addEventListener('click',()=>{soundEnabled=!soundEnabled;els.sound.classList.toggle('active',soundEnabled);els.sound.setAttribute('aria-pressed',String(soundEnabled));beep(880,.07)});els.popular.addEventListener('click',e=>{const b=e.target.closest('[data-material]');if(b)openDetails(b.dataset.material)});els.special.addEventListener('click',e=>{const b=e.target.closest('[data-query]');if(!b)return;els.search.value=b.dataset.query;els.search.dispatchEvent(new Event('input',{bubbles:true}));$('#catalog').scrollIntoView({behavior:reduceMotion?'auto':'smooth'})});els.backToTop.addEventListener('click',()=>scrollTo({top:0,behavior:reduceMotion?'auto':'smooth'}));addEventListener('scroll',()=>els.backToTop.classList.toggle('visible',scrollY>650),{passive:true})}
function init(){fillFilters();renderPopular();MATERIALS.filter(m=>m.family!=='Поддержки').forEach(m=>els.modelMaterial.add(new Option(m.name,m.name)));els.modelMaterial.value=findMaterial('PETG')?.name||MATERIALS[0].name;renderMaterials();renderCompare();updateSupport();renderQuests();bindEvents();observeReveals(document.querySelectorAll('.tip-card,.support-picker,.support-info'));loadEasterEggs()}
init();